GO
/****** Object:  Table [dbo].[tra_TransactionTypeSettings_OS]    Script Date: 2/6/2019 6:01:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tra_TransactionTypeSettings_OS](
	[TTTS_ID] [int] IDENTITY(1,1) NOT NULL,
	[SECURITY_TYPE_CODE_ID] [nvarchar](50) NOT NULL,
	[TRANS_TYPE_CODE_ID] [nvarchar](50) NOT NULL,
	[MODE_OF_ACQUIS_CODE_ID] [nvarchar](50) NOT NULL,
	[ACTION_CODE_ID] [nvarchar](50) NOT NULL,
	[IMPT_POST_SHARE_QTY_CODE_ID] [nvarchar](50) NOT NULL,
	[CONTRA_TRADE_CODE_ID] [nvarchar](50) NOT NULL,
	[CREATED_BY] [int] NOT NULL,
	[CREATED_ON] [datetime] NOT NULL,
	[UPDATED_BY] [int] NULL,
	[UPDATED_ON] [datetime] NULL,
	[EXEMPT_PRE_FOR_MODE_OF_ACQUISITION] [int] NOT NULL DEFAULT ((1)),
PRIMARY KEY CLUSTERED 
(
	[TTTS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
