using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace InsiderTradingExcelWriter.ExcelFacade
{
    public class ConstantEnum
    {
        #region Enum OpenXMLStyleIndex
        public enum OpenXMLStyleIndex
        {
            DEFAULT_NO_STYLE = 0,

            #region Text Styles
            #region Primary text styles : 24
            TEXT_CUSTOM_GRAY_BACKGROUND_BOLD_WITH_BORDERS,
            TEXT_CUSTOM_GRAY_BACKGROUND_BOLD_RIGHT_ALIGN_WITH_BORDERS,
            TEXT_CUSTOM_GRAY_BACKGROUND_BOLD_V_ALIGN_CENTER_WITH_BORDERS,

            TEXT_CUSTOM_GRAY_BACKGROUND_BOLD_CENTER_ALIGN_WITH_BORDERS,
            TEXT_CUSTOM_GRAY_BACKGROUND_BOLD_H_CENTER_V_BOTTOM_WITH_BORDERS,
            TEXT_CUSTOM_GRAY_BACKGROUND_NORMAL_CENTER_ALIGN_WITH_BORDERS,

            TEXT_CUSTOM_GREEN_BACKGROUND_BOLD_CENTER_ALIGN_WITH_BORDERS,

            TEXT_CUSTOM_BLUE_BACKGROUND_BOLD_CENTER_ALIGN_WITH_BORDERS,
            TEXT_CUSTOM_LIGHT_BLUE_BACKGROUND_BOLD_CENTER_ALIGN,
            TEXT_CUSTOM_LIGHT_BLUE_BACKGROUND_BOLD_LEFT_ALIGN,
            TEXT_CUSTOM_LIGHT_BLUE_BACKGROUND_BOLD_RIGHT_ALIGN,

            TEXT_PLAIN_BACKGROUND_BOLD_WITH_BORDERS,
            TEXT_PLAIN_BACKGROUND_BOLD_CENTER_ALIGN_WITH_BORDERS,

            TEXT_PLAIN_BACKGROUND_NORMAL_WITH_BORDERS,
            TEXT_PLAIN_BACKGROUND_NORMAL_GRAY_COLOR_TEXT_WITH_SMALL_SIZE,
            TEXT_PLAIN_BACKGROUND_NORMAL_TEXT_WITH_SMALL_SIZE,
            TEXT_PLAIN_BACKGROUND_NORMAL_CENTER_ALIGN_WITH_BORDERS,
            TEXT_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_WITH_BORDERS,
            TEXT_PLAIN_BACKGROUND_NORMAL_WITH_DASHED_BOOTOM_BORDER,
            TEXT_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_WITH_BORDERS,

            TEXT_LIGHT_BLUE_BACKGROUND_BOLD_WITH_BORDERS,
            TEXT_PLANE_BACKGROUND_WINGDINGS_FONT_RED,
            TEXT_PLANE_BACKGROUND_WINGDINGS_FONT_GREEN,
            TEXT_PLANE_BACKGROUND_WINGDINGS_FONT_ORANGE,
            #endregion // Primary text styles : 24

            #region Text styles with Indentation : 16
            TEXT_PLAIN_BACKGROUND_BOLD_WITH_BORDERS_INDENT_1,
            TEXT_PLAIN_BACKGROUND_BOLD_WITH_BORDERS_INDENT_2,
            TEXT_PLAIN_BACKGROUND_BOLD_WITH_BORDERS_INDENT_3,
            TEXT_PLAIN_BACKGROUND_BOLD_WITH_BORDERS_INDENT_4,
            TEXT_PLAIN_BACKGROUND_BOLD_WITH_BORDERS_INDENT_5,
            TEXT_PLAIN_BACKGROUND_BOLD_WITH_BORDERS_INDENT_6,
            TEXT_PLAIN_BACKGROUND_BOLD_WITH_BORDERS_INDENT_7,
            TEXT_PLAIN_BACKGROUND_BOLD_WITH_BORDERS_INDENT_8,

            TEXT_PLAIN_BACKGROUND_NORMAL_WITH_BORDERS_INDENT_1,
            TEXT_PLAIN_BACKGROUND_NORMAL_WITH_BORDERS_INDENT_2,
            TEXT_PLAIN_BACKGROUND_NORMAL_WITH_BORDERS_INDENT_3,
            TEXT_PLAIN_BACKGROUND_NORMAL_WITH_BORDERS_INDENT_4,
            TEXT_PLAIN_BACKGROUND_NORMAL_WITH_BORDERS_INDENT_5,
            TEXT_PLAIN_BACKGROUND_NORMAL_WITH_BORDERS_INDENT_6,
            TEXT_PLAIN_BACKGROUND_NORMAL_WITH_BORDERS_INDENT_7,
            TEXT_PLAIN_BACKGROUND_NORMAL_WITH_BORDERS_INDENT_8,
            #endregion // Text styles with Indentation : 16

            #region Text styles with no border with indentation : 29
            // : 4
            TEXT_PLAIN_BACKGROUND_BOLD_WITH_NO_BORDER_NO_WRAP,
            TEXT_PLAIN_BACKGROUND_BOLD_WITH_NO_BORDER,
            TEXT_PLAIN_BACKGROUND_BOLD_CENTER_ALIGN_WITH_NO_BORDER,
            TEXT_PLAIN_BACKGROUND_NORMAL_WITH_NO_BORDER,
            // : 4

            TEXT_PLAIN_BACKGROUND_BOLD_INDENT_1,
            TEXT_PLAIN_BACKGROUND_BOLD_INDENT_2,
            TEXT_PLAIN_BACKGROUND_BOLD_INDENT_3,
            TEXT_PLAIN_BACKGROUND_BOLD_INDENT_4,
            TEXT_PLAIN_BACKGROUND_BOLD_INDENT_5,
            TEXT_PLAIN_BACKGROUND_BOLD_INDENT_6,
            TEXT_PLAIN_BACKGROUND_BOLD_INDENT_7,
            TEXT_PLAIN_BACKGROUND_BOLD_INDENT_8,
            TEXT_PLAIN_BACKGROUND_BOLD_NO_IDENT,

            TEXT_PLAIN_BACKGROUND_NORMAL_INDENT_1,
            TEXT_PLAIN_BACKGROUND_NORMAL_INDENT_2,
            TEXT_PLAIN_BACKGROUND_NORMAL_INDENT_3,
            TEXT_PLAIN_BACKGROUND_NORMAL_INDENT_4,
            TEXT_PLAIN_BACKGROUND_NORMAL_INDENT_5,
            TEXT_PLAIN_BACKGROUND_NORMAL_INDENT_6,
            TEXT_PLAIN_BACKGROUND_NORMAL_INDENT_7,
            TEXT_PLAIN_BACKGROUND_NORMAL_INDENT_8,
            TEXT_PLAIN_BACKGROUND_NORMAL_NO_IDENT,

            // : 8
            TEXT_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN,
            TEXT_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN,
            TEXT_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_BORDER,
            TEXT_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_RIGHT_BORDER,

            TEXT_PLAIN_BACKGROUND_NORMAL_CENTER_ALIGN,
            TEXT_PLAIN_BACKGROUND_BOLD_CENTER_ALIGN,

            TEXT_PLAIN_BACKGROUND_NORMAL_NO_IDENT_GENERAL,
            TEXT_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BOTTOM_BORDER,
            // : 8
            #endregion // Text styles with no border with indentation : 29


            #region Text styles with bottom  border : 22
            // : 2
            TEXT_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_BOTTOM_BORDER,
            TEXT_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_BOTTOM_BORDER,
            // : 2

            #region Text styles with no bottom with indentation : 20
            TEXT_PLAIN_BACKGROUND_BOLD_INDENT_1_BOTTOM_BORDER,
            TEXT_PLAIN_BACKGROUND_BOLD_INDENT_2_BOTTOM_BORDER,
            TEXT_PLAIN_BACKGROUND_BOLD_INDENT_3_BOTTOM_BORDER,
            TEXT_PLAIN_BACKGROUND_BOLD_INDENT_4_BOTTOM_BORDER,
            TEXT_PLAIN_BACKGROUND_BOLD_INDENT_5_BOTTOM_BORDER,
            TEXT_PLAIN_BACKGROUND_BOLD_INDENT_6_BOTTOM_BORDER,
            TEXT_PLAIN_BACKGROUND_BOLD_INDENT_7_BOTTOM_BORDER,
            TEXT_PLAIN_BACKGROUND_BOLD_INDENT_8_BOTTOM_BORDER,
            TEXT_PLAIN_BACKGROUND_BOLD_NO_IDENT_BOTTOM_BORDER,

            TEXT_PLAIN_BACKGROUND_NORMAL_INDENT_1_BOTTOM_BORDER,
            TEXT_PLAIN_BACKGROUND_NORMAL_INDENT_2_BOTTOM_BORDER,
            TEXT_PLAIN_BACKGROUND_NORMAL_INDENT_3_BOTTOM_BORDER,
            TEXT_PLAIN_BACKGROUND_NORMAL_INDENT_4_BOTTOM_BORDER,
            TEXT_PLAIN_BACKGROUND_NORMAL_INDENT_5_BOTTOM_BORDER,
            TEXT_PLAIN_BACKGROUND_NORMAL_INDENT_6_BOTTOM_BORDER,
            TEXT_PLAIN_BACKGROUND_NORMAL_INDENT_7_BOTTOM_BORDER,
            TEXT_PLAIN_BACKGROUND_NORMAL_INDENT_8_BOTTOM_BORDER,
            TEXT_PLAIN_BACKGROUND_NORMAL_NO_IDENT_BOTTOM_BORDER,

            TEXT_PLAIN_BACKGROUND_NORMAL_CENTER_ALIGN_BOTTOM_BORDER,
            TEXT_PLAIN_BACKGROUND_BOLD_CENTER_ALIGN_BOTTOM_BORDER,
            #endregion // Text styles with bottom border with indentation : 20
            #endregion // Text styles with bottom  border : 22


            #region Text style with light and dark yellow background : 2
            TEXT_LIGHT_YELLOW_BACKGROUND_NORMAL_NO_BORDER,
            TEXT_DARK_YELLOW_BACKGROUND_NORMAL_TOP_BORDER,
            #endregion // Text style with light and dark yellow background : 2


            #region Arial Narrow 10 : 11
            ARIAL_NARROW_10_TEXT_CUSTOM_GRAY_BACKGROUND_BOLD_WITH_BORDERS,
            ARIAL_NARROW_10_TEXT_CUSTOM_GRAY_BACKGROUND_BOLD_RIGHT_ALIGN_WITH_BORDERS,

            ARIAL_NARROW_10_TEXT_PLAIN_BACKGROUND_BOLD_WITH_BORDERS,
            ARIAL_NARROW_10_TEXT_PLAIN_BACKGROUND_NORMAL_WITH_BORDERS,

            ARIAL_NARROW_10_TEXT_PLAIN_BACKGROUND_BOLD_WITH_NO_BORDER,

            ARIAL_NARROW_10_TEXT_CUSTOM_GRAY_BACKGROUND_BOLD_V_ALIGN_CENTER_WITH_BORDERS,
            ARIAL_NARROW_10_TEXT_CUSTOM_GRAY_BACKGROUND_BOLD_CENTER_ALIGN_WITH_BORDERS,
            ARIAL_NARROW_10_TEXT_PLAIN_BACKGROUND_NORMAL_CENTER_ALIGN_WITH_BORDERS,
            ARIAL_NARROW_10_TEXT_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_WITH_BORDERS,
            ARIAL_NARROW_10_TEXT_CUSTOM_GRAY_BACKGROUND_NORMAL_CENTER_ALIGN_WITH_BORDERS,

            ARIAL_NARROW_10_TEXT_AQUA_BACKGROUND_BOLD_WITH_BORDERS,

            #endregion // Arial Narrow 10 : 11

            #region Link for both text and numeric : 2
            LINK_PLAIN_BACKGROUND_NORMAL_UNDERLINE_BLUE_COLOR_CENTER_ALIGN,
            LINK_PLAIN_BACKGROUND_NORMAL_UNDERLINE_BLUE_COLOR_CENTER_ALIGN_WITH_BORDERS,
            #endregion // Link for both text and numeric : 2
            #endregion // Text Styles

            #region Numeric styles
            #region no decimal with border : 18
            NO_DECIMAL_NUMERIC_WITHOUT_COMMA_PLAIN_BACKGROUND_NORMAL_LEFT_ALIGN_WITH_BORDERS,
            NO_DECIMAL_NUMERIC_WITHOUT_COMMA_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_WITH_BORDERS,

            NO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_WITH_BORDERS,
            NO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_CENTER_ALIGN_WITH_BORDERS,

            NO_DECIMAL_NUMERIC_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_WITH_BORDERS,
            NO_DECIMAL_NUMERIC_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_WITH_BORDERS,

            // Added by Arundhati 2-Jul-2014
            NO_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_WITH_BORDERS,
            NO_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_WITH_BORDERS,

            NO_DECIMAL_LIGHT_GRAY_BACKGROUND_NORMAL_RIGHT_ALIGN_WITH_BORDERS,
            NO_DECIMAL_LIGHT_GRAY_BACKGROUND_BOLD_RIGHT_ALIGN_WITH_BORDERS,

            NO_DECIMAL_NUMERIC_WITH_THOUSAND_SEPARATOR_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_WITH_BORDERS,
            NO_DECIMAL_NUMERIC_WITH_THOUSAND_SEPARATOR_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_WITH_BORDERS,

            //new additions by Lankesh Begins
            NO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_WITH_ALL_BORDERS,
            NO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_WITH_ALL_BORDERS,
            //new additions by Lankesh Ends

            // Added by Arundhati 2-Jul-2014
            NO_DECIMAL_NUMERIC_LIGHT_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_WITH_ALL_BORDERS,
            NO_DECIMAL_NUMERIC_LIGHT_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_WITH_ALL_BORDERS,

            /* Arial Narrow 10 */
            ARIAL_NARROW_10_NO_DECIMAL_NUMERIC_WITHOUT_COMMA_PLAIN_BACKGROUND_NORMAL_LEFT_ALIGN_WITH_BORDERS,
            ARIAL_NARROW_10_NO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_CENTER_ALIGN_WITH_BORDERS,
            /* Arial Narrow 10 */
            #endregion // no decimal with border : 18

            #region No decimal with no border : 12
            NO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN,
            NO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN,

            NO_DECIMAL_NUMERIC_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN,
            NO_DECIMAL_NUMERIC_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN,

            // Added by Arundhati 2-Jul-2014
            NO_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN,
            NO_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN,

            NO_DECIMAL_NUMERIC_LIGHT_GRAY_BACKGROUND_NORMAL_RIGHT_ALIGN,
            NO_DECIMAL_NUMERIC_LIGHT_GRAY_BACKGROUND_BOLD_RIGHT_ALIGN,

            NO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN,
            NO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN,

            // Added by Arundhati 2-Jul-2014
            NO_DECIMAL_NUMERIC_LIGHT_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN,
            NO_DECIMAL_NUMERIC_LIGHT_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN,

            #endregion // No decimal with no border : 12

            #region No decimal with top border : 12
            NO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_TOP_BORDER,
            NO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BORDER,

            NO_DECIMAL_NUMERIC_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BORDER,
            NO_DECIMAL_NUMERIC_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_TOP_BORDER,

            // Added by Arundhati 2-Jul-2014
            NO_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BORDER,
            NO_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_TOP_BORDER,

            NO_DECIMAL_NUMERIC_LIGHT_GRAY_BACKGROUND_NORMAL_RIGHT_ALIGN_TOP_BORDER,
            NO_DECIMAL_NUMERIC_LIGHT_GRAY_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BORDER,

            NO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_TOP_BORDER,
            NO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BORDER,

            // Added by Arundhati 2-Jul-2014
            NO_DECIMAL_NUMERIC_LIGHT_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_TOP_BORDER,
            NO_DECIMAL_NUMERIC_LIGHT_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BORDER,
            #endregion // No decimal with top border : 12

            #region No decimal with top and bootom border : 12
            NO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_TOP_BOTTOM_BORDER,
            NO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BOTTOM_BORDER,

            NO_DECIMAL_NUMERIC_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BOTTOM_BORDER,
            NO_DECIMAL_NUMERIC_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_TOP_BOTTOM_BORDER,

            // Added by Arundhati 2-Jul-2014
            NO_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BOTTOM_BORDER,
            NO_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_TOP_BOTTOM_BORDER,

            NO_DECIMAL_NUMERIC_LIGHT_GRAY_BACKGROUND_NORMAL_RIGHT_ALIGN_TOP_BOTTOM_BORDER,
            NO_DECIMAL_NUMERIC_LIGHT_GRAY_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BOTTOM_BORDER,

            NO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_TOP_BOTTOM_BORDER,
            NO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BOTTOM_BORDER,

            // Added by Arundhati 2-Jul-2014
            NO_DECIMAL_NUMERIC_LIGHT_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_TOP_BOTTOM_BORDER,
            NO_DECIMAL_NUMERIC_LIGHT_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BOTTOM_BORDER,
            #endregion // No decimal with top and bootom border : 12


            #region 1 decimal with border : 10
            //new additions by Lankesh Begins
            ONE_DECIMAL_NUMERIC_PLAIN_NORMAL_RIGHT_ALIGN_WITH_ALL_BORDERS,
            ONE_DECIMAL_NUMERIC_PLAIN_BOLD_RIGHT_ALIGN_WITH_ALL_BORDERS,

            ONE_DECIMAL_NUMERIC_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_WITH_ALL_BORDERS,
            // Added by Arundhati 2-Jul-2014
            ONE_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_WITH_ALL_BORDERS,

            ONE_DECIMAL_NUMERIC_LIGHT_GRAY_BACKGROUND_NORMAL_RIGHT_ALIGN_WITH_BORDERS,
            ONE_DECIMAL_NUMERIC_LIGHT_GRAY_BACKGROUND_BOLD_RIGHT_ALIGN_WITH_BORDERS,

            ONE_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_WITH_ALL_BORDERS,
            ONE_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_WITH_ALL_BORDERS,

            // Added by Arundhati 2-Jul-2014
            ONE_DECIMAL_NUMERIC_LIGHT_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_WITH_ALL_BORDERS,
            ONE_DECIMAL_NUMERIC_LIGHT_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_WITH_ALL_BORDERS,

            //new additions by Lankesh Ends
            #endregion // 1 decimal with border : 10

            #region 1 decimal with no border : 9
            ONE_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN,
            ONE_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN,

            ONE_DECIMAL_NUMERIC_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN,

            // Added by Arundhati 2-Jul-2014
            ONE_DECIMAL_NUMERIC_LIGHT_GRAY_BACKGROUND_NORMAL_RIGHT_ALIGN,
            ONE_DECIMAL_NUMERIC_LIGHT_GRAY_BACKGROUND_BOLD_RIGHT_ALIGN,

            ONE_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN,
            ONE_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN,

            // Added by Arundhati 2-Jul-2014
            ONE_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN,
            ONE_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN,
            #endregion // 1 decimal with no border : 9

            #region 1 decimal with top border : 10
            ONE_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_TOP_BORDER,
            ONE_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BORDER,

            ONE_DECIMAL_NUMERIC_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BORDER,

            // Added by Arundhati 2-Jul-2014
            ONE_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BORDER,

            ONE_DECIMAL_NUMERIC_LIGHT_GRAY_BACKGROUND_NORMAL_RIGHT_ALIGN_TOP_BORDER,
            ONE_DECIMAL_NUMERIC_LIGHT_GRAY_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BORDER,

            ONE_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_TOP_BORDER,
            ONE_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BORDER,

            // Added by Arundhati 2-Jul-2014
            ONE_DECIMAL_NUMERIC_LIGHT_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_TOP_BORDER,
            ONE_DECIMAL_NUMERIC_LIGHT_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BORDER,
            #endregion // 1 decimal with top border : 10

            #region 1 decimal with top and bottom border : 10
            ONE_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_TOP_BOTTOM_BORDER,
            ONE_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BOTTOM_BORDER,

            ONE_DECIMAL_NUMERIC_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BOTTOM_BORDER,
            // Added by Arundhati 2-Jul-2014
            ONE_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BOTTOM_BORDER,

            ONE_DECIMAL_NUMERIC_LIGHT_GRAY_BACKGROUND_NORMAL_RIGHT_ALIGN_TOP_BOTTOM_BORDER,
            ONE_DECIMAL_NUMERIC_LIGHT_GRAY_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BOTTOM_BORDER,

            ONE_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_TOP_BOTTOM_BORDER,
            ONE_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BOTTOM_BORDER,

            // Added by Arundhati 2-Jul-2014
            ONE_DECIMAL_NUMERIC_LIGHT_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_TOP_BOTTOM_BORDER,
            ONE_DECIMAL_NUMERIC_LIGHT_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BOTTOM_BORDER,
            #endregion // 1 decimal with top and bottom border : 10


            #region 2 decimal with border : 19
            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_WITH_BORDERS,
            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_WITH_BORDERS,

            TWO_DECIMAL_NUMERIC_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_WITH_BORDERS,
            TWO_DECIMAL_NUMERIC_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_WITH_BORDERS,

            // Added by Arundhati 2-Jul-2014
            TWO_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_WITH_BORDERS,
            TWO_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_WITH_BORDERS,

            TWO_DECIMAL_NUMERIC_LIGHT_GRAY_BACKGROUND_NORMAL_RIGHT_ALIGN_WITH_BORDERS,
            TWO_DECIMAL_NUMERIC_LIGHT_GRAY_BACKGROUND_BOLD_RIGHT_ALIGN_WITH_BORDERS,

            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RED_COLOR_RIGHT_ALIGN_WITH_NO_BORDER,
            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RED_COLOR_RIGHT_ALIGN_WITH_BORDERS,

            TWO_DECIMAL_NUMERIC_PLAIN_BOLD_RIGHT_ALIGN_WITH_DASHED_BOTTOM_BORDER,


            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_WITH_BORDERS_WITHOUT_BRACKET,
            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_WITH_BORDERS_WITHOUT_BRACKET,

            TWO_DECIMAL_NUMERIC_LIGHT_BLUE_BACKGROUND_BOLD_RIGHT_ALIGN_WITH_BORDERS,

            //new additions by Lankesh Begins
            TWO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_WITH_ALL_BORDERS,
            TWO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_WITH_ALL_BORDERS,

            // Added by Arundhati 2-Jul-2014
            TWO_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_WITH_ALL_BORDERS,
            TWO_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_WITH_ALL_BORDERS,

            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_WITHOUT_BORDERS_WITH_NO_BRACKET,
            //new additions by Lankesh Ends
            #endregion // 2 decimal with border : 19

            #region 2 decimal with no border : 10
            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN,
            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN,

            TWO_DECIMAL_NUMERIC_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN,
            TWO_DECIMAL_NUMERIC_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN,

            // Added by Arundhati 2-Jul-2014
            TWO_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN,
            TWO_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN,

            TWO_DECIMAL_NUMERIC_LIGHT_GRAY_BACKGROUND_NORMAL_RIGHT_ALIGN,
            TWO_DECIMAL_NUMERIC_LIGHT_GRAY_BACKGROUND_BOLD_RIGHT_ALIGN,

            TWO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN,
            TWO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN,
            #endregion // 2 decimal with no border : 10

            #region 2 decimal with top border : 10
            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_TOP_BORDER,
            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BORDER,

            TWO_DECIMAL_NUMERIC_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BORDER,
            TWO_DECIMAL_NUMERIC_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_TOP_BORDER,

            // Added by Arundhati 2-Jul-2014
            TWO_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BORDER,
            TWO_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_TOP_BORDER,

            TWO_DECIMAL_NUMERIC_LIGHT_GRAY_BACKGROUND_NORMAL_RIGHT_ALIGN_TOP_BORDER,
            TWO_DECIMAL_NUMERIC_LIGHT_GRAY_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BORDER,

            TWO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_TOP_BORDER,
            TWO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BORDER,
            #endregion // 2 decimal with top border : 10

            #region 2 decimal with top and bottom border : 10
            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_TOP_BOTTOM_BORDER,
            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BOTTOM_BORDER,

            TWO_DECIMAL_NUMERIC_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BOTTOM_BORDER,
            TWO_DECIMAL_NUMERIC_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_TOP_BOTTOM_BORDER,

            // Added by Arundhati 2-Jul-2014
            TWO_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BOTTOM_BORDER,
            TWO_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_TOP_BOTTOM_BORDER,

            TWO_DECIMAL_NUMERIC_LIGHT_GRAY_BACKGROUND_NORMAL_RIGHT_ALIGN_TOP_BOTTOM_BORDER,
            TWO_DECIMAL_NUMERIC_LIGHT_GRAY_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BOTTOM_BORDER,

            TWO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_TOP_BOTTOM_BORDER,
            TWO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_TOP_BOTTOM_BORDER,
            #endregion // 2 decimal with top and bottom border : 10

            #region Arial Narrow 10 with border : 7
            ARIAL_NARROW_10_TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_WITH_BORDERS,
            ARIAL_NARROW_10_TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_WITH_BORDERS,

            ARIAL_NARROW_10_TWO_DECIMAL_NUMERIC_LIGHT_GRAY_BACKGROUND_NORMAL_RIGHT_ALIGN_WITH_BORDERS,
            ARIAL_NARROW_10_TWO_DECIMAL_NUMERIC_LIGHT_GRAY_BACKGROUND_BOLD_RIGHT_ALIGN_WITH_BORDERS,

            ARIAL_NARROW_10_TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_WITH_BORDERS_WITHOUT_BRACKET,
            ARIAL_NARROW_10_TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_WITH_BORDERS_WITHOUT_BRACKET,

            ARIAL_NARROW_10_TWO_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_WITH_BORDERS,
            #endregion // Arial Narrow 10 with border : 7

            //4 decimal with border : 1
            FOUR_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_WITH_BORDERS_WITHOUT_BRACKET,

            #region 6 decimal with border : 6
            SIX_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_WITH_BORDERS,
            SIX_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_WITH_BORDERS,

            SIX_DECIMAL_LIGHT_GRAY_BACKGROUND_NORMAL_RIGHT_ALIGN_WITH_BORDERS,
            SIX_DECIMAL_LIGHT_GRAY_BACKGROUND_BOLD_RIGHT_ALIGN_WITH_BORDERS,

            SIX_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_WITH_DASHED_BOTTOM_BORDERS,
            SIX_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_WITH_NO_BORDERS,
            #endregion // 6 decimal with border : 6

            //8 decimal with border : 1
            EIGHT_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_WITH_BORDERS,

            #region Numeric with left border : 18
            NO_DECIMAL_NUMERIC_WITH_THOUSAND_SEPARATOR_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_BORDER,
            NO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_BORDER,

            ONE_DECIMAL_NUMERIC_PLAIN_NORMAL_RIGHT_ALIGN_WITH_LEFT_BORDER,
            ONE_DECIMAL_NUMERIC_PLAIN_BOLD_RIGHT_ALIGN_WITH_LEFT_BORDER,

            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_BORDER,
            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_BORDER,


            NO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_BORDER,
            NO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_BORDER,

            ONE_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_BORDER,
            ONE_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_BORDER,

            TWO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_BORDER,
            TWO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_BORDER,

            // Added by Arundhati 2-Jul-2014
            NO_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_BORDER,
            NO_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_BORDER,

            ONE_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_BORDER,
            ONE_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_BORDER,

            TWO_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_BORDER,
            TWO_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_BORDER,

            #endregion // Numeric with left border : 18

            #region Numeric with left, bottom border : 18
            NO_DECIMAL_NUMERIC_WITH_THOUSAND_SEPARATOR_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_BOTTOM_BORDER,
            NO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_BOTTOM_BORDER,

            ONE_DECIMAL_NUMERIC_PLAIN_NORMAL_RIGHT_ALIGN_WITH_LEFT_BOTTOM_BORDER,
            ONE_DECIMAL_NUMERIC_PLAIN_BOLD_RIGHT_ALIGN_WITH_LEFT_BOTTOM_BORDER,

            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_BOTTOM_BORDER,
            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_BOTTOM_BORDER,


            NO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_BOTTOM_BORDER,
            NO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_BOTTOM_BORDER,

            ONE_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_BOTTOM_BORDER,
            ONE_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_BOTTOM_BORDER,

            TWO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_BOTTOM_BORDER,
            TWO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_BOTTOM_BORDER,

            // Added by Arundhati 2-Jul-2014
            NO_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_BOTTOM_BORDER,
            NO_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_BOTTOM_BORDER,

            ONE_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_BOTTOM_BORDER,
            ONE_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_BOTTOM_BORDER,

            TWO_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_BOTTOM_BORDER,
            TWO_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_BOTTOM_BORDER,

            #endregion // Numeric with left, bottom border : 18

            #region Numeric with right border : 18
            NO_DECIMAL_NUMERIC_WITH_THOUSAND_SEPARATOR_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_RIGHT_BORDER,
            NO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_RIGHT_BORDER,

            ONE_DECIMAL_NUMERIC_PLAIN_NORMAL_RIGHT_ALIGN_WITH_RIGHT_BORDER,
            ONE_DECIMAL_NUMERIC_PLAIN_BOLD_RIGHT_ALIGN_WITH_RIGHT_BORDER,

            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_RIGHT_BORDER,
            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_RIGHT_BORDER,

            NO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_RIGHT_BORDER,
            NO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_RIGHT_BORDER,

            ONE_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_RIGHT_BORDER,
            ONE_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_RIGHT_BORDER,

            TWO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_RIGHT_BORDER,
            TWO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_RIGHT_BORDER,

            // Added by Arundhati 2-Jul-2014
            NO_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_RIGHT_BORDER,
            NO_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_RIGHT_BORDER,

            ONE_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_RIGHT_BORDER,
            ONE_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_RIGHT_BORDER,

            TWO_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_RIGHT_BORDER,
            TWO_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_RIGHT_BORDER,
            #endregion // Numeric with right border : 18

            #region Numeric with right, bottom border : 18
            NO_DECIMAL_NUMERIC_WITH_THOUSAND_SEPARATOR_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_RIGHT_BOTTOM_BORDER,
            NO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_RIGHT_BOTTOM_BORDER,

            ONE_DECIMAL_NUMERIC_PLAIN_NORMAL_RIGHT_ALIGN_WITH_RIGHT_BOTTOM_BORDER,
            ONE_DECIMAL_NUMERIC_PLAIN_BOLD_RIGHT_ALIGN_WITH_RIGHT_BOTTOM_BORDER,

            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_RIGHT_BOTTOM_BORDER,
            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_RIGHT_BOTTOM_BORDER,


            NO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_RIGHT_BOTTOM_BORDER,
            NO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_RIGHT_BOTTOM_BORDER,

            ONE_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_RIGHT_BOTTOM_BORDER,
            ONE_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_RIGHT_BOTTOM_BORDER,

            TWO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_RIGHT_BOTTOM_BORDER,
            TWO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_RIGHT_BOTTOM_BORDER,

            // Added by Arundhati 2-Jul-2014
            NO_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_RIGHT_BOTTOM_BORDER,
            NO_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_RIGHT_BOTTOM_BORDER,

            ONE_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_RIGHT_BOTTOM_BORDER,
            ONE_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_RIGHT_BOTTOM_BORDER,

            TWO_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_RIGHT_BOTTOM_BORDER,
            TWO_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_RIGHT_BOTTOM_BORDER,
            #endregion // Numeric with right, bottom border : 18

            #region Numeric with bottom border : 18
            NO_DECIMAL_NUMERIC_WITH_THOUSAND_SEPARATOR_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_BOTTOM_BORDER,
            NO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_BOTTOM_BORDER,

            ONE_DECIMAL_NUMERIC_PLAIN_NORMAL_RIGHT_ALIGN_WITH_BOTTOM_BORDER,
            ONE_DECIMAL_NUMERIC_PLAIN_BOLD_RIGHT_ALIGN_WITH_BOTTOM_BORDER,

            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_BOTTOM_BORDER,
            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_BOTTOM_BORDER,


            NO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_BOTTOM_BORDER,
            NO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_BOTTOM_BORDER,

            ONE_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_BOTTOM_BORDER,
            ONE_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_BOTTOM_BORDER,

            TWO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_BOTTOM_BORDER,
            TWO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_BOTTOM_BORDER,

            // Added by Arundhati 2-Jul-2014
            NO_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_BOTTOM_BORDER,
            NO_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_BOTTOM_BORDER,

            ONE_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_BOTTOM_BORDER,
            ONE_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_BOTTOM_BORDER,

            TWO_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_BOTTOM_BORDER,
            TWO_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_BOTTOM_BORDER,
            #endregion // Numeric with right, bottom border : 18

            #region Numeric with left, right border : 18
            NO_DECIMAL_NUMERIC_WITH_THOUSAND_SEPARATOR_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_RIGHT_BORDER,
            NO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_RIGHT_BORDER,

            ONE_DECIMAL_NUMERIC_PLAIN_NORMAL_RIGHT_ALIGN_WITH_LEFT_RIGHT_BORDER,
            ONE_DECIMAL_NUMERIC_PLAIN_BOLD_RIGHT_ALIGN_WITH_LEFT_RIGHT_BORDER,

            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_RIGHT_BORDER,
            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_RIGHT_BORDER,


            NO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_RIGHT_BORDER,
            NO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_RIGHT_BORDER,

            ONE_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_RIGHT_BORDER,
            ONE_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_RIGHT_BORDER,

            TWO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_RIGHT_BORDER,
            TWO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_RIGHT_BORDER,

            // Added by Arundhati 2-Jul-2014
            NO_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_RIGHT_BORDER,
            NO_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_RIGHT_BORDER,

            ONE_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_RIGHT_BORDER,
            ONE_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_RIGHT_BORDER,

            TWO_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_RIGHT_BORDER,
            TWO_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_RIGHT_BORDER,
            #endregion // Numeric with right, left, right border : 18

            #region Numeric with left, right, bottom border : 18
            NO_DECIMAL_NUMERIC_WITH_THOUSAND_SEPARATOR_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_RIGHT_BOTTOM_BORDER,
            NO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_RIGHT_BOTTOM_BORDER,

            ONE_DECIMAL_NUMERIC_PLAIN_NORMAL_RIGHT_ALIGN_WITH_LEFT_RIGHT_BOTTOM_BORDER,
            ONE_DECIMAL_NUMERIC_PLAIN_BOLD_RIGHT_ALIGN_WITH_LEFT_RIGHT_BOTTOM_BORDER,

            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_RIGHT_BOTTOM_BORDER,
            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_RIGHT_BOTTOM_BORDER,


            NO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_RIGHT_BOTTOM_BORDER,
            NO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_RIGHT_BOTTOM_BORDER,

            ONE_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_RIGHT_BOTTOM_BORDER,
            ONE_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_RIGHT_BOTTOM_BORDER,

            TWO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_RIGHT_BOTTOM_BORDER,
            TWO_DECIMAL_NUMERIC_LIGHT_YELLOW_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_RIGHT_BOTTOM_BORDER,

            // Added by Arundhati 2-Jul-2014
            NO_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_RIGHT_BOTTOM_BORDER,
            NO_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_RIGHT_BOTTOM_BORDER,

            ONE_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_RIGHT_BOTTOM_BORDER,
            ONE_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_RIGHT_BOTTOM_BORDER,

            TWO_DECIMAL_NUMERIC_AQUA_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_RIGHT_BOTTOM_BORDER,
            TWO_DECIMAL_NUMERIC_AQUA_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_RIGHT_BOTTOM_BORDER,

            #endregion // Numeric with right, left, right, bottom border : 18


            #region Numeric with left, top border : 6
            NO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_TOP_BORDER,
            NO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_TOP_BORDER,

            ONE_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_TOP_BORDER,
            ONE_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_TOP_BORDER,

            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_TOP_BORDER,
            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_TOP_BORDER,
            #endregion // Numeric with left, top border : 6

            #region Numeric with left, top, bottom border : 6
            NO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_TOP_BOTTOM_BORDER,
            NO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_TOP_BOTTOM_BORDER,

            ONE_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_TOP_BOTTOM_BORDER,
            ONE_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_TOP_BOTTOM_BORDER,

            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_TOP_BOTTOM_BORDER,
            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_TOP_BOTTOM_BORDER,
            #endregion // Numeric with left, top, bottom border : 6

            #region Numeric with right, top border : 6
            NO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_RIGHT_TOP_BORDER,
            NO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_RIGHT_TOP_BORDER,

            ONE_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_RIGHT_TOP_BORDER,
            ONE_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_RIGHT_TOP_BORDER,

            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_RIGHT_TOP_BORDER,
            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_RIGHT_TOP_BORDER,
            #endregion // Numeric with right, top border : 6

            #region Numeric with right, top, bottom border
            NO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_RIGHT_TOP_BOTTOM_BORDER,
            NO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_RIGHT_TOP_BOTTOM_BORDER,

            ONE_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_RIGHT_TOP_BOTTOM_BORDER,
            ONE_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_RIGHT_TOP_BOTTOM_BORDER,

            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_RIGHT_TOP_BOTTOM_BORDER,
            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_RIGHT_TOP_BOTTOM_BORDER,
            #endregion // Numeric with right, top, bottom border : 6

            #region Numeric with left, right, top border : 6
            NO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_RIGHT_TOP_BORDER,
            NO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_RIGHT_TOP_BORDER,

            ONE_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_RIGHT_TOP_BORDER,
            ONE_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_RIGHT_TOP_BORDER,

            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_NORMAL_RIGHT_ALIGN_LEFT_RIGHT_TOP_BORDER,
            TWO_DECIMAL_NUMERIC_PLAIN_BACKGROUND_BOLD_RIGHT_ALIGN_LEFT_RIGHT_TOP_BORDER,
            #endregion // Numeric with left, right, top border : 6
            #endregion // Numeric styles

            #region DateTime : 6
            DATETIME_PLAIN_BACKGROUND_BOLD_LEFT_ALIGN_WITH_NO_BORDERS_dd_mm_yyyy_h_mm_AM_PM,
            DATETIME_PLAIN_BACKGROUND_BOLD_LEFT_ALIGN_WITH_NO_BORDERS_dd_mm_yyyy_h_mm_AM_PM_RED,

            DATETIME_PLAIN_BACKGROUND_NORMAL_LEFT_ALIGN_WITH_NO_BORDERS_dd_mm_yyyy_HH_mm,
            DATETIME_PLAIN_BACKGROUND_BOLD_LEFT_ALIGN_WITH_NO_BORDERS_dd_mm_yyyy_HH_mm,
            DATETIME_PLAIN_BACKGROUND_BOLD_LEFT_ALIGN_WITH_NO_BORDERS_dd_mm_yyyy_HH_mm_RED,

            /* Arial Narrow 10 */
            ARIAL_NARROW_10_DATETIME_PLAIN_BACKGROUND_BOLD_LEFT_ALIGN_WITH_NO_BORDERS_dd_mm_yyyy_h_mm_AM_PM
            /* Arial Narrow 10 */
            #endregion // DateTime : 6
        }
        #endregion // Enum OpenXMLStyleIndex

        #region PaperSize
        public sealed class PaperSize
        {
            public const uint LETTER_PAPER = 1; //Letter paper (8.5 in. by 11 in.)
            public const uint LETTER_SMALL_PAPER = 2;// = Letter small paper (8.5 in. by 11 in.)
            public const uint TABLOID_PAPER = 3;// = Tabloid paper (11 in. by 17 in.)
            public const uint LEDGER_PAPER = 4;// = Ledger paper (17 in. by 11 in.)
            public const uint LEGAL_PAPER = 5;// = Legal paper (8.5 in. by 14 in.)
            public const uint STATEMENT_PAPER = 6;// = Statement paper (5.5 in. by 8.5 in.)
            public const uint EXECUTIVE_PAPER = 7;// = Executive paper (7.25 in. by 10.5 in.)
            public const uint A3_PAPER = 8;// = A3 paper (297 mm by 420 mm)
            public const uint A4_PAPER = 9;// = A4 paper (210 mm by 297 mm)
            public const uint A4_SMALL_PAPER = 10;// = A4 small paper (210 mm by 297 mm)
            public const uint A5_PAPER = 11;// = A5 paper (148 mm by 210 mm)
            public const uint B4_PAPER = 12;// = B4 paper (250 mm by 353 mm)
            public const uint B5_PAPER = 13;// = B5 paper (176 mm by 250 mm)
            public const uint FOLIO_PAPER = 14;// = Folio paper (8.5 in. by 13 in.)
            public const uint QUARTO_PAPER = 15;// = Quarto paper (215 mm by 275 mm)
            public const uint STANDARD_PAPER_10_14 = 16;// = Standard paper (10 in. by 14 in.)
            public const uint STANDARD_PAPER_11_17 = 17;// = Standard paper (11 in. by 17 in.)
            public const uint NOTE_PAPER = 18;// = Note paper (8.5 in. by 11 in.)
            public const uint ENVELOPE_3_8 = 19;// = #9 envelope (3.875 in. by 8.875 in.)
            public const uint ENVELOPE_4_9 = 20;// = #10 envelope (4.125 in. by 9.5 in.)
            public const uint ENVELOPE_4_10 = 21;// = #11 envelope (4.5 in. by 10.375 in.)
            public const uint ENVELOPE_4_11_8 = 22;// = #12 envelope (4.75 in. by 11 in.)
            public const uint ENVELOPE_5_11 = 23;// = #14 envelope (5 in. by 11.5 in.)
            public const uint C_PAPER = 24;// = C paper (17 in. by 22 in.)
            public const uint D_PAPER = 25;// = D paper (22 in. by 34 in.)
            public const uint E_PAPER = 26;// = E paper (34 in. by 44 in.)
            public const uint DL_ENVELOPE = 27;// = DL envelope (110 mm by 220 mm)
            public const uint C5_ENVELOPE = 28;// = C5 envelope (162 mm by 229 mm)
            public const uint C3_ENVELOPE = 29;// = C3 envelope (324 mm by 458 mm)
            public const uint C4_ENVELOPE = 30;// = C4 envelope (229 mm by 324 mm)
            public const uint C6_ENVELOPE = 31;// = C6 envelope (114 mm by 162 mm)
            public const uint C65_ENVELOPE = 32;// = C65 envelope (114 mm by 229 mm)
            public const uint B4_ENVELOPE = 33;// = B4 envelope (250 mm by 353 mm)
            public const uint B5_ENVELOPE = 34;// = B5 envelope (176 mm by 250 mm)
            public const uint B6_ENVELOPE = 35;// = B6 envelope (176 mm by 125 mm)
            public const uint ITALY_ENVELOPE = 36;// = Italy envelope (110 mm by 230 mm)
            public const uint MONARCH_ENVELOPE = 37;// = Monarch envelope (3.875 in. by 7.5 in.).
            public const uint ENVELOPE_6_3_BY_4 = 38;// = 6 3/4 envelope (3.625 in. by 6.5 in.)
            public const uint US_STANDARD_FANFOLD = 39;// = US standard fanfold (14.875 in. by 11 in.)
            public const uint GERMAN_STANDARD_FANFOLD = 40;// = German standard fanfold (8.5 in. by 12 in.)
            public const uint US_LEGAL_FANFOLD = 41;// = German legal fanfold (8.5 in. by 13 in.)
            public const uint ISO_B4 = 42;// = ISO B4 (250 mm by 353 mm)
            public const uint JAPANESE_DOUBLE_POSTCARD = 43;// = Japanese double postcard (200 mm by 148 mm)
            public const uint STANDARD_PAPER_9_11 = 44;// = Standard paper (9 in. by 11 in.)
            public const uint STANDARD_PAPER_10_11 = 45;// = Standard paper (10 in. by 11 in.)
            public const uint STANDARD_PAPER_15_11 = 46;// = Standard paper (15 in. by 11 in.)
            public const uint INVITE_ENVELOPE = 47;// = Invite envelope (220 mm by 220 mm)
            public const uint LETTER_EXTRA_PAPER = 50;// = Letter extra paper (9.275 in. by 12 in.)
            public const uint LEGAL_EXTRA_PAPER = 51;// = Legal extra paper (9.275 in. by 15 in.)
            public const uint TABLOID_EXTRA_PAPER = 52;// = Tabloid extra paper (11.69 in. by 18 in.)
            public const uint A4_EXTRA_PAPER = 53;// = A4 extra paper (236 mm by 322 mm)
            public const uint LETTER_TRANSVERSE_PAPER = 54;// = Letter transverse paper (8.275 in. by 11 in.)
            public const uint A4_TRANSVERSE_PAPER = 55;// = A4 transverse paper (210 mm by 297 mm)
            public const uint LETTER_EXTRA_TRANSVERSE_PAPER = 56;// = Letter extra transverse paper (9.275 in. by 12 in.)
            public const uint SUPERA_A4_PAPER = 57;// = SuperA/SuperA/A4 paper (227 mm by 356 mm)
            public const uint SUPERB_A3_PAPER = 58;// = SuperB/SuperB/A3 paper (305 mm by 487 mm)
            public const uint LETTER_PLUS_PAPER = 59;// = Letter plus paper (8.5 in. by 12.69 in.)
            public const uint A4_PLUS_PAPER = 60;// = A4 plus paper (210 mm by 330 mm)
            public const uint A5_TRANSVERSE_PAPER = 61;// = A5 transverse paper (148 mm by 210 mm)
            public const uint JIS_B5_TRANSVERSE_PAPER = 62;// = JIS B5 transverse paper (182 mm by 257 mm)
            public const uint A3_EXTRA_PAPER = 63;// = A3 extra paper (322 mm by 445 mm)
            public const uint A5_EXTRA_PAPER = 64;// = A5 extra paper (174 mm by 235 mm)
            public const uint ISO_B5_EXTRA_PAPER = 65;// = ISO B5 extra paper (201 mm by 276 mm)
            public const uint A2_PAPER = 66;// = A2 paper (420 mm by 594 mm)
            public const uint A3_TRANSVERSE_PAPER = 67;// = A3 transverse paper (297 mm by 420 mm)
            public const uint A3_EXTRA_TRANSVERSE_PAPER = 68;// = A3 extra transverse paper (322 mm by 445 mm)
        }
        #endregion// PaperSize
    }
}
