/*
	Created By  :	Akhilesh Kamate
	Created On 	:	29-Mar-2016
	Description :	This type is used to stored NSE Details
	
*/

IF EXISTS(SELECT NAME FROM SYS.PROCEDURES WHERE NAME = 'st_du_OnGoingContDiscData')
BEGIN
	DROP PROCEDURE st_du_OnGoingContDiscData
END
GO

IF EXISTS (SELECT 1 FROM SYS.TYPES ST JOIN SYS.SCHEMAS SS ON ST.schema_id = SS.schema_id WHERE (ST.name = N'du_type_OnGoingContDiscData') AND (SS.name = N'dbo'))
BEGIN
	DROP TYPE du_type_OnGoingContDiscData
END
GO

IF NOT EXISTS (SELECT 1 FROM SYS.TYPES ST JOIN SYS.SCHEMAS SS ON ST.schema_id = SS.schema_id WHERE (ST.name = N'du_type_OnGoingContDiscData') AND (SS.name = N'dbo'))
BEGIN
	CREATE TYPE du_type_OnGoingContDiscData AS TABLE 
	(
		ENTITY_ID	VARCHAR(500),
		EMP_NO	VARCHAR(500),
		TRD_NO	VARCHAR(500),
		ENT_FULL_NAME	VARCHAR(500),
		ENTITY_DP_AC_NO	VARCHAR(500),
		TRD_DT	DATETIME,
		SMST_ISIN_CODE	VARCHAR(500),
		SMST_SECURITY_NAME	VARCHAR(500),
		TRD_SEM_ID	VARCHAR(500),
		TRD_BUY_SELL_FLG	VARCHAR(500),
		TRD_QTY	DECIMAL(18,2),
		TRD_PRICE	DECIMAL(18,2),
		ENTITY_PAN	VARCHAR(20)
	)	
END
GO
