-- ======================================================================================================
-- Author      : Rajashri Sathe																		
-- CREATED DATE: 21-APR-2020                                                 							
-- Description : Update the data in tra_TemplateMaster          		
-- ======================================================================================================


update tra_TemplateMaster set Contents='<div style="margin: 30px; width: 1080px;font-family: ''Roboto'', sans-serif;font-size:12px; padding-left:10px;">       <div>        <div>         Hi,         <p>Please note that the following unpublished price sensitive information (UPSI) has been shared:</p>         <br />         Category of Information: [CategoryOfInformation]<br />         Reason for sharing information: [ReasonForSharingInformation]<br />         Mode of sharing information: [ModeOfSharingInformation]<br />         Date and Time of sharing information:  [DateOfSharingInformation]: [TimeOfSharingInformation]<br /><br />           Information shared by : <br />         Name: [SharedByName]<br />         Email:[SharedByEmailID]<br />          <table>         <br /><br />         Information updated on MyInsider by:<br />         Name: [NameOfTheUserWhoUpdatedThisInformation]          </div>       </div>      </div>'
 where  TemplateName = 'UPSI Updated' AND IsActive = 1 AND CommunicationModeCodeId='156011'

update tra_TemplateMaster set Contents='<div style="margin: 30px; width: 1080px;font-family: ''Roboto'', sans-serif;font-size:12px; padding-left:10px;">       <div>        <div>         Hi,         <p>Please note that the following unpublished price sensitive information (UPSI) that was shared has now been published:</p>         <br />         Category of Information: [CategoryOfInformation]<br />         Reason for sharing information: [ReasonForSharingInformation]<br />         Mode of sharing information: [ModeOfSharingInformation]<br />         Date and Time of sharing information:  [DateOfSharingInformation]: [TimeOfSharingInformation]<br />         Date of publishing: [DateOfPublishing]<br /><br />         Information shared by : <br />         Name: [SharedByName]<br />         Email:[SharedByEmailID]<br /><br />                  <table>           <br /><br />Information updated on MyInsider by:<br />         Name: [NameOfTheUserWhoUpdatedThisInformation]          </div>       </div>      </div>'
 where  TemplateName = 'UPSI Published' AND IsActive = 1 AND CommunicationModeCodeId='156012'

 --update tra_TemplateMaster set Contents='<div style="margin: 30px; width: 1080px;font-family: ''Roboto'', sans-serif;font-size:12px; padding-left:10px;">         <div>          <div>           Hi [FirstName] [LastName],             <p>With reference to the Insider Trading Code of Conduct, a set of questions have been enabled on MyInsider from [DateOfActivationOfMCQ]. You are required to answer these questions within [FrequencyDuration] days of activation failing which your account will be deactivated.   You will get a total of [NoOfAttempts] chances to answer these questions correctly.</p>            <p>Please get in touch with your administrator in case of any queries.</p>            <br />           Regards,<br />           [CoName]          </div>         </div>        </div>'
 --where  TemplateName = 'Activation of MCQ' AND IsActive = 1 AND CommunicationModeCodeId='156013'

 --update tra_TemplateMaster set Contents='<div style="margin: 30px; width: 1080px;font-family: ''Roboto'', sans-serif;font-size:12px; padding-left:10px;">       <div>        <div>         Hi ,           <p>Please note that the following account has been blocked on MyInsider: Emp id : [EmployeeID] Emp Name: [FirstName] [LastName]</p>          <p>User name: [UserName] Please reactivate the account.<p>         </div>       </div>       </div>'
 --where  TemplateName = 'Employee Account blocked' AND IsActive = 1 AND CommunicationModeCodeId='156014'

 --update tra_TemplateMaster set Contents='<div style="margin: 30px; width: 1080px;font-family: ''Roboto'', sans-serif;font-size:12px; padding-left:10px;">       <div>        <div>         Hi ,           <p>Please note that the following account has been reactivated on MyInsider: </P>                  Employee ID : [EmployeeID]<br/>          Employee Name: [FirstName] [LastName]<br/>         User name: [UserName]<br/>         </div>       </div>      </div>'
 --where  TemplateName = 'Employee Account activated' AND IsActive = 1 AND CommunicationModeCodeId='156015'

 --update tra_TemplateMaster set Contents='Dear |~|FIRST_NAME|~|,    Welcome to MyInsider!!    MyInsider is a web based platform which would help you to manage, monitor, track and report your dealings in securities of RBL Bank Limited and thus ensure compliance with the provisions of the said Code and Insider Trading Regulations.     1. Kindly follow the link provided for receiving your login details:    Go to the link: |~|APP_URL_ANCHOR|~|  Or  Copy-paste the link in browser URL:  |~|APP_URL|~|    2. Enter following details to generate and reset your password:    Company Name: RBL Bank  Login ID: |~|LOGIN_ID|~|    EMAIL Id: Your official email id    3. You will receive an email with details of URL through which your password can be reset.     4. On receiving this email:  - Click on the link provided  - Enter your password and reconfirm the same  - This reset password shall be your password for further logins    For any assistance/ clarification, please contact the Company Secretarial Department on securitiescomplianceofficer@rblbank.com',
 --Subject='MyInsider: Login Details' 
 --where  TemplateName = 'Login Details to Insider Employee' AND IsActive = 1 AND CommunicationModeCodeId='156002'

 update tra_TemplateMaster set Contents='Dear |~|FIRST_NAME|~|,    Welcome to MyInsider!!    MyInsider is a web based platform which would help you to manage, monitor, track and report your dealings in securities of RBL Bank Limited and thus ensure compliance with the provisions of the said Code and Insider Trading Regulations.     1. Kindly follow the link provided for receiving your login details:    Go to the link: |~|APP_URL_ANCHOR|~|  Or  Copy-paste the link in browser URL:  |~|APP_URL|~|    2. Enter following details to generate and reset your password:    Company Name: RBL Bank  Login ID: |~|LOGIN_ID|~|    EMAIL Id: Your official email id    3. You will receive an email with details of URL through which your password can be reset.     4. On receiving this email:  - Click on the link provided  - Enter your password and reconfirm the same  - This reset password shall be your password for further logins    For any assistance/ clarification, please contact the Company Secretarial Department on securitiescomplianceofficer@rblbank.com',
 Subject='MyInsider: Login Details' 
 where  TemplateName = 'LOGIN DETAILS MAIL – To Designated Person' AND IsActive = 1 AND CommunicationModeCodeId='156002'

 update tra_TemplateMaster set Contents='Dear Compliance Officer, <br><br>    |~|FIRST_NAME|~| |~|LAST_NAME|~| has requested for a Pre-clearance for trading in the securities of ________________________-.<br><br>    Request you to login to MyInsider to approve / reject the pre-clearance.<br><br>  '
 where  TemplateName = 'PRE-CLEARANCE REQUEST INTIMATION– To Compliance Officer' AND IsActive = 1 AND CommunicationModeCodeId='156002'

 update tra_TemplateMaster set Contents='Dear Mr/Ms.|~|FIRST_NAME|~| |~|LAST_NAME|~|,<br>    In accordance with the provisions of ___________________________ Code of Conduct for Prevention of Insider Trading (Code), you as a Designated Person of the Company are required to disclose annual statements of the holding in the shares of ___________________ by you and/or your Immediate Relatives and of any other person for whom you take trading decisions, to the Compliance Officer as on 31st March every year. <br><br>    You are requested to login to your MyInsider account and submit your details before 15th April every year. <br><br>    Please ignore if already submitted.<br><br><br>  '
 where  TemplateName = 'SUBMISSION OF ANNUAL DECLARATION – To Designated Person' AND IsActive = 1 AND CommunicationModeCodeId='156002'

 update tra_TemplateMaster set Contents='Dear Compliance Officer,<br><br>    Mr/Ms.|~|FIRST_NAME|~| |~|LAST_NAME|~| has submitted the trade details. Please login to MyInsider to check the status of Form C and if generated submit to the Stock Exchange.<br>    Please ignore if already submitted to Stock Exchanges.<br><br><br>'
 where  TemplateName = 'SUBMISSION OF TRADE DETAILS – To Compliance Officer' AND IsActive = 1 AND CommunicationModeCodeId='156002'


 