--Add column in usr_Authentication
IF NOT EXISTS(SELECT SYSTAB.NAME FROM SYS.TABLES SYSTAB INNER JOIN SYS.COLUMNS SYSCOL ON SYSTAB.OBJECT_ID = SYSCOL.OBJECT_ID 
WHERE SYSTAB.NAME = 'usr_Authentication' AND SYSCOL.NAME = 'SaltValue')
BEGIN
	ALTER TABLE usr_Authentication ADD SaltValue NVARCHAR(500) NULL
END
GO

IF NOT EXISTS(SELECT SYSTAB.NAME FROM SYS.TABLES SYSTAB INNER JOIN SYS.COLUMNS SYSCOL ON SYSTAB.OBJECT_ID = SYSCOL.OBJECT_ID 
WHERE SYSTAB.NAME = 'usr_PasswordHistory' AND SYSCOL.NAME = 'SaltValue')
BEGIN
	ALTER TABLE usr_PasswordHistory ADD SaltValue NVARCHAR(500) NULL
END
GO