
IF NOT EXISTS(SELECT SECURITY_TYPE_CODE_ID FROM tra_TransactionTypeSettings 
                           WHERE SECURITY_TYPE_CODE_ID=139001 and TRANS_TYPE_CODE_ID=143002 and MODE_OF_ACQUIS_CODE_ID=149009)
BEGIN
INSERT INTO tra_TransactionTypeSettings
                                                              
select 139001 SECURITY_TYPE_CODE_ID,     143002 TRANS_TYPE_CODE_ID, 149009 MODE_OF_ACQUIS_CODE_ID,
504002 ACTION_CODE_ID,     505002 IMPT_POST_SHARE_QTY_CODE_ID,      506002 CONTRA_TRADE_CODE_ID,       1 CREATED_BY,
GETDATE() CREATED_ON,      1 UPDATED_BY, GETDATE()     UPDATED_ON ,1 EXEMPT_PRE_FOR_MODE_OF_ACQUISITION

END
